steps:
  # .envにCloud Buildの代入変数を埋め込むステップを追加する
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "DATABASE_URL=${_DATABASE_URL}" >> .env
        echo "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}" >> .env
        echo "AWS_REGION=${_AWS_REGION}" >> .env
        echo "AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_MAP_MAPID=${_NEXT_PUBLIC_GOOGLE_MAP_MAPID}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_API_KEY}" >> .env
        echo "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}" >> .env
        echo "DIRECT_URL=${_DIRECT_URL}" >> .env

        docker build  --build-arg DATABASE_URL=${_DATABASE_URL} \
                      --build-arg AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID} \
                      --build-arg AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY} \
                      --build-arg AWS_REGION=${_AWS_REGION} \
                      --build-arg AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME} \
                      --build-arg NEXT_PUBLIC_GOOGLE_MAP_MAPID=${_NEXT_PUBLIC_GOOGLE_MAP_MAPID} \
                      --build-arg NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_API_KEY} \
                      --build-arg NEXTAUTH_SECRET=${_NEXTAUTH_SECRET} \
                      --build-arg DIRECT_URL=${_DIRECT_URL} \
                      -f Dockerfile \
                      -t gcr.io/$PROJECT_ID/next13-ecsite:$COMMIT_SHA .

  # ビルドしたコンテナイメージをArtifact Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/next13-ecsite:$COMMIT_SHA"]

  # Cloud Run デプロイステップ
  - id: deploy-cloud-run
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - 'run'
      - 'deploy'
      - 'next13-ecsite'
      - '--image'
      - 'gcr.io/$PROJECT_ID/next13-ecsite:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - >-
        DATABASE_URL=${_DATABASE_URL},
        AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID},
        AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY},
        AWS_REGION=${_AWS_REGION},
        AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME},
        NEXT_PUBLIC_GOOGLE_MAP_MAPID=${_NEXT_PUBLIC_GOOGLE_MAP_MAPID},
        NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_API_KEY},
        NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},
        DIRECT_URL=${_DIRECT_URL}
images:
  - "gcr.io/$PROJECT_ID/next13-ecsite:$COMMIT_SHA"
timeout: 900s




# steps:
#   # ビルドステップ
#   - id: build-frontend
#     name: "gcr.io/cloud-builders/docker"
#     entrypoint: "bash"
#     args:
#       - -c
#       - >-
#         docker build
#         --file=Dockerfile
#         --tag=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
#         --tag=gcr.io/$PROJECT_ID/$REPO_NAME:latest
#         --cache-from=gcr.io/$PROJECT_ID/$REPO_NAME:latest
#         .
#     secretEnv:
#       - DATABASE_URL
#       - AWS_ACCESS_KEY_ID
#       - AWS_SECRET_ACCESS_KEY
#       - AWS_REGION
#       - AWS_S3_BUCKET_NAME
#       - NEXT_PUBLIC_GOOGLE_MAP_MAPID
#       - NEXT_PUBLIC_GOOGLE_MAP_API_KEY
#       - NEXTAUTH_SECRET
#       - DIRECT_URL

#   # プッシュステップ
#   - id: push-frontend
#     name: "gcr.io/cloud-builders/docker"
#     args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']


#     secretEnv:
#       - DATABASE_URL
#       - AWS_ACCESS_KEY_ID
#       - AWS_SECRET_ACCESS_KEY
#       - AWS_REGION
#       - AWS_S3_BUCKET_NAME
#       - NEXT_PUBLIC_GOOGLE_MAP_MAPID
#       - NEXT_PUBLIC_GOOGLE_MAP_API_KEY
#       - NEXTAUTH_SECRET
#       - DIRECT_URL

# secrets:
#   - kmsKeyName: "projects/$PROJECT_ID/locations/global/keyRings/KEY_RING/cryptoKeys/KEY_NAME"
#     secretEnv:
#       DATABASE_URL: "projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest"
#       AWS_ACCESS_KEY_ID: "projects/$PROJECT_ID/secrets/AWS_ACCESS_KEY_ID/versions/latest"
#       AWS_SECRET_ACCESS_KEY: "projects/$PROJECT_ID/secrets/AWS_SECRET_ACCESS_KEY/versions/latest"
#       AWS_REGION: "projects/$PROJECT_ID/secrets/AWS_REGION/versions/latest"
#       AWS_S3_BUCKET_NAME: "projects/$PROJECT_ID/secrets/AWS_S3_BUCKET_NAME/versions/latest"
#       NEXT_PUBLIC_GOOGLE_MAP_MAPID: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_MAP_MAPID/versions/latest"
#       NEXT_PUBLIC_GOOGLE_MAP_API_KEY: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_MAP_API_KEY/versions/latest"
#       NEXTAUTH_SECRET: "projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/latest"
#       DIRECT_URL: "projects/$PROJECT_ID/secrets/DIRECT_URL/versions/latest"
