steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret={ecsite} > .env.production
    id: 'fetch-secret'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg'
      - 'ENV_FILE=.env.production'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: 'Build'

options:
  logging: CLOUD_LOGGING_ONLY  # ログをCloud Loggingに保存
  logsBucket: 'gs://your-logs-bucket'  # ログバケットの指定（必要に応じて）
substitutions:
  _AR_HOSTNAME: 'your-ar-hostname'
  _SERVICE_NAME: 'your-service-name'
  _REPO_NAME: 'your-repo-name'
  _PROJECT_ID: 'your-project-id'
  _COMMIT_SHA: 'your-commit-sha'
