steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=ecsite > .env.production

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - >-
        gcr.io/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/ecsite:${COMMIT_SHA}
      - '--build-arg'
      - 'ENV_FILE=.env.production'
      - '.'
    id: 'Build'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ecsite'  # Cloud Runサービス名
      - '--image'
      - 'gcr.io/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/ecsite:${COMMIT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'  # 公開する場合
    id: 'Deploy to Cloud Run'

options:
  logging: CLOUD_LOGGING_ONLY  # Save logs to Cloud Logging

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-artifacts/'
    paths:
      - '.env.production'
