steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
    secretEnv:
      - _DATABASE_URL
      - _AWS_ACCESS_KEY_ID
      - _AWS_SECRET_ACCESS_KEY
      - _AWS_REGION
      - _AWS_S3_BUCKET_NAME
      - _NEXT_PUBLIC_GOOGLE_MAP_MAPID
      - _NEXT_PUBLIC_GOOGLE_MAP_API_KEY
      - _NEXTAUTH_SECRET
      - _DIRECT_URL

  # プッシュステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Cloud Run デプロイステップ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'next13-ecsite', 
      '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', 
      '--region', 'asia-northeast1', 
      '--platform', 'managed',
      '--set-env-vars', 
      'DATABASE_URL=${_DATABASE_URL},AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID},AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY},AWS_REGION=${_AWS_REGION},AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME},NEXT_PUBLIC_GOOGLE_MAP_MAPID=${_NEXT_PUBLIC_GOOGLE_MAP_MAPID},NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_API_KEY},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},DIRECT_URL=${_DIRECT_URL}'
    ]
    secretEnv:
      - _DATABASE_URL
      - _AWS_ACCESS_KEY_ID
      - _AWS_SECRET_ACCESS_KEY
      - _AWS_REGION
      - _AWS_S3_BUCKET_NAME
      - _NEXT_PUBLIC_GOOGLE_MAP_MAPID
      - _NEXT_PUBLIC_GOOGLE_MAP_API_KEY
      - _NEXTAUTH_SECRET
      - _DIRECT_URL

secrets:
  - kmsKeyName: "projects/PROJECT_ID/locations/global/keyRings/KEY_RING/cryptoKeys/KEY_NAME"
    secretEnv:
      _DATABASE_URL: "projects/PROJECT_ID/secrets/_DATABASE_URL/versions/latest"
      _AWS_ACCESS_KEY_ID: "projects/PROJECT_ID/secrets/_AWS_ACCESS_KEY_ID/versions/latest"
      _AWS_SECRET_ACCESS_KEY: "projects/PROJECT_ID/secrets/_AWS_SECRET_ACCESS_KEY/versions/latest"
      _AWS_REGION: "projects/PROJECT_ID/secrets/_AWS_REGION/versions/latest"
      _AWS_S3_BUCKET_NAME: "projects/PROJECT_ID/secrets/_AWS_S3_BUCKET_NAME/versions/latest"
      _NEXT_PUBLIC_GOOGLE_MAP_MAPID: "projects/PROJECT_ID/secrets/_NEXT_PUBLIC_GOOGLE_MAP_MAPID/versions/latest"
      _NEXT_PUBLIC_GOOGLE_MAP_API_KEY: "projects/PROJECT_ID/secrets/_NEXT_PUBLIC_GOOGLE_MAP_API_KEY/versions/latest"
      _NEXTAUTH_SECRET: "projects/PROJECT_ID/secrets/_NEXTAUTH_SECRET/versions/latest"
      _DIRECT_URL: "projects/PROJECT_ID/secrets/_DIRECT_URL/versions/latest"

options:
  logging: CLOUD_LOGGING_ONLY
