steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=ecsite > .env.production
    id: 'fetch-secret'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - >-
        ${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/ecsite:${COMMIT_SHA}
      - '--build-arg'
      - 'ENV_FILE=.env.production'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: 'Build'

options:
  logging: CLOUD_LOGGING_ONLY  # Save logs to Cloud Logging