steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=ecsite > .env.production

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - >-
        gcr.io/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/ecsite:${COMMIT_SHA}
      - '--build-arg'
      - 'ENV_FILE=.env.production'
      - '.'
    id: 'Build'

options:
  logging: CLOUD_LOGGING_ONLY  # Save logs to Cloud Logging

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-artifacts/'
    paths:
      - '.env.production'
