services:

  front:
    build: 
      context: .
      target: runner
    ports:
      - 3000:3000
    environment:
      -  WATCHPACK_POLLING=true
    tty: true
    env_file:
      - .env.production

#   front_dev:
#     build:
#       context: .
#       target: dev
#     volumes: 
#       - ./:/app
#     ports:
#       - 3000:3000
#       - 5555:5555
#     environment:
#       - WATCHPACK_POLLING=true
#     tty: true
#     command: "npm run dev"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     volumes:
#       - db:/var/lib/postgresql/ecsite
#     ports:
#       - 5432:5432
#     env_file:
#       - .env

# volumes:
#   db: